name: Built and deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKES: ${{ secrets.FIREBASE_TOKEN }}
    
